language: python
python:
- 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- mkdir /website/themes
- cd /website/themes
- git init
- git remote add origin -f https://github.com/getpelican/pelican-themes.git
- git config core.sparseCheckout true
- echo "/pelican-bootstrap3/" >> .git/info/sparse-checkout
- git pull origin master 
- make publish

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: output
  target_branch: master
  on:
    branch: source